org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

mod_id=enhancedai
mod_name=Enhanced AI
mod_license=All Rights Reserved
mod_version=4.0.0.0-beta
mod_group_id=insane96mcp.enhancedai

insanelib_version=2.1.1.0-beta
insanelib_version_range=[2.1.1.0-beta,)
mpr_version=6.0.1.2-beta