modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Insane96/EnhancedAI/issues"
[[mods]]
modId="enhancedai"
version="${file.jarVersion}"
displayName="Enhanced AI"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhanced-ai"
# logoFile="examplemod.png"
# credits="Thanks for this example mod goes to Java"
authors="Insane96MCP"
description='''
Give more AI variants to mobs, from Creepers breaching to Zombies mining.

Also His name is John Cena.
'''
[[dependencies.enhancedai]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enhancedai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enhancedai]]
    modId = "insanelib"
    mandatory = true
    versionRange = "[1.9.1,)"
    ordering = "NONE"
    side = "BOTH"